name: PresidioDeidentificationForOHNLPTK
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - transformers
  - conda-pack
  - pip:
      - ohnlptk-xlang-python==1.1.0
      - presidio-analyzer==2.2.33
      - presidio-anonymizer==2.2.33
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0.tar.gz
