name: PresidioDeidentificationForOHNLPTK
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - transformers=4.32.1
  - conda-pack
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cpuonly=2.0
  - charset_normalizer=3.4.0
  - pip:
      - ohnlptk-xlang-python==1.1.0
      - presidio-analyzer==2.2.33
      - presidio-anonymizer==2.2.33
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0.tar.gz
